### ISSUE TITLE
Entity-entity solid collisions do not seem to be working

### ISSUE THREAD

**Issue by KCreator** [Tesserex/C--MegaMan-Engine#11]
In the latest master version, it seems entities cannot collide with each other similar to map statics, for example disappearing blocks, conveyer wheel entity, moving platforms, etc.

This is using unmodified xml files and is easily reproducible.

**Comment by Tesserex** [comment]
I believe that's because that master version was pushed without a thorough fix to all the xml entity files. There was a change in the way the collision system worked which requires all the hitboxes to be rewritten in the xml, which hasn't been done. So essentially collision is turned off for those entities.

**Comment by KCreator** [comment]
Well, I investigated the matter (Using breakpoints during the entity collision check) . and it seems the collision "properties" are not having the "Blocking" Boolean value set correctly.

I'm not sure how exactly to format it, it might be my fault. So I guess I will wait until you have enough time to work on the project, and document more of the features. Thank you for being incredibly quick with that response.
